config/routes.rb
Rails.application.routes.draw do

  root 'trees#index'

  resources :scenarios
  devise_for :users

  scope '/admin' do
    resources :users
  end

  resources :trees
  get '/cenario/:tree_id', to: 'nodes#cenario'
  post '/conditions_sub_trees', to: 'nodes#conditions_sub_trees'
  get '/cenario_resultado/:tree_id', to: 'nodes#cenario_resultado'
  post '/path_for_result', to: 'nodes#path_for_result'

end

app/models/node.rb
class Node < ActiveRecord::Base
    belongs_to :tree
    has_many :scenarios,dependent: :destroy
    has_ancestry


    def get_variables_conditions(tree_id)
        variable = {}
        nodes = self.class.where(tree_id: tree_id).order("variable ASC")
        nodes.each { |node|
            name = node.variable.to_sym
            if !variable.key? name
                variable[name] =  Array.new()
            end
            node_obj = OpenStruct.new({name: node.condition, result: (node.result == 'f') ? 0 : node.result})
            if !variable[name].detect {|node| node.name == node_obj.name}
                variable[name] << node_obj
            end
        }
        return variable
    end

    def get_conditions_sub_tree(variable,condition,tree_id)
        array_node = Array.new
        nodes = self.class.where(variable: variable, condition: condition, tree_id: tree_id)

        nodes.each do |node|
            array_node << node.descendants
        end
        return array_node
    end

    def path_for_result(result)

        nodes = self.class.where(result: result)
        paths = Array.new()
        result = Hash.new()
        nodes.each { |node|
            a = Array.new()
            node.path.each { |node|
                a << OpenStruct.new({variable: node.variable,condition: node.condition})
            }
            text = self.path_for_result_to_text a
            result = {id: node.id,text: text}
            paths << result
        }
        return paths
    end

    def path_for_result_by_id(id)
        node = self.class.find id
        a = Array.new()
        node.path.each { |node|
            a << OpenStruct.new({variable: node.variable,condition: node.condition})
        }
        return a
    end

    def path_for_result_to_text(paths)
        text = ''
        paths.each_with_index do |node, index|
          text << "<p>#{index + 1}º - #{node.variable} #{node.condition}</p>"
        end
        return text
    end

    def extract_tree(file,start_search,end_search,variaveis,tree_id)
        nome_no = ''
        tree = Array.new
        auxiliar_tree = Array.new
        nivel = 0
        condicao = ''
        resultado = ''
        id = 0
        identity = tree_id.to_s + '0'
        id_pai = identity + '1'
        array =  IO.readlines(file)[start_search..end_search]
        array.each do |line|
            line.delete! "'"
            node = self.class.new
            nivel = line.count('|')
            nome_no = variaveis.select { |variavel| line.include? variavel }
            nome_no = nome_no.first.to_str
            condicao = line.partition(nome_no).last.strip
            no_resultado = condicao.index(':')
            resultado = false
            if !no_resultado.nil?
                resultado = condicao[no_resultado + 1.. - 1]
                resultado.strip!
                no_resultado_numero = resultado.index(' ')
                resultado_numero = resultado[no_resultado_numero .. -1]
                resultado = resultado[0 .. no_resultado_numero -1]
                resultado.strip!
                resultado_numero.strip!
                condicao = condicao[0 .. no_resultado - 1 ]
            end
            condicao.strip!
            id += 1
            hash = {
                id: identity + id.to_s,
                tree_id: tree_id,
                id_pai: id_pai ,
                level: nivel ,
                variable: nome_no.parameterize.underscore ,
                condition: condicao ,
                result: resultado,
                result_numbers: resultado_numero,
                created_at: Time.now,
                updated_at:Time.now
            }
            if nivel == 0
                auxiliar_tree = auxiliar_tree.unshift(hash)
                node = node.to_obj hash
            elsif nivel > auxiliar_tree[0][:level]
                id_pai = auxiliar_tree[0][:id]
                auxiliar_tree = auxiliar_tree.unshift(hash)
                node = node.to_obj hash
                node.parent_id = id_pai
            else
                id_pai = auxiliar_tree.select {|no| no[:level] == nivel-1}
                id_pai =  id_pai.first
                id_pai = id_pai[:id]
                auxiliar_tree = auxiliar_tree.unshift(hash)
                node = node.to_obj hash
                node.parent_id = id_pai
            end
            node.save
        end
    end

    def to_obj(hash)
        hash.except! :id_pai
        JSON.parse(
            hash.to_json,
            object_class: Node
            )
    end

    def extract_variables(file,start_search,end_search)
        variaveis =[]
        array =  IO.readlines(file)[start_search..end_search]
        array.each do |variavel|
            variaveis << variavel.strip
        end
        return variaveis
    end
end

app/controllers/nodes_controller.rb
class NodesController < ApplicationController
  before_action :set_node, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /nodes
  # GET /nodes.json
  def index
    @nodes = Node.all
  end

  def cenario
    @id = params['tree_id']
    @nodes = Node.new
    @nodes = @nodes.get_variables_conditions(@id)
    render "index"
  end

  def cenario_resultado
    @id = params['tree_id']
    @results = Array.new
    nodes = Node.where("tree_id = #{params['tree_id']} AND result <> 'f'")
    nodes.each { |node|
      @results << node.result
    }
    @results = @results.uniq
    render "cenario_resultado"
  end

  #fazer um if caso o primeiro click seja o final precisa trazer o result e o id dele
  #verificar o bug de nao funcionar caso seja um array de arrays
  #colocar o campo text para o nome
  #embelezar o show dos cenarios
  def conditions_sub_trees
    @nodes_sub_tree = Node.new
    @nodes_sub_tree = @nodes_sub_tree.get_conditions_sub_tree(params['variable'],params['condition'],params['tree_id'])
    respond_to do |format|
        if @nodes_sub_tree
            format.json { render :json => @nodes_sub_tree, :status => 200 }
        end
    end
  end

  def path_for_result
    node = Node.new
    @path_for_result = node.path_for_result(params['result'])
    respond_to do |format|
      if @path_for_result
          format.json { render :json => @path_for_result, :status => 200 }
      end
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def node_params
    params.require(:node).permit(:tree_id, :variable, :condition, :result, :level)
  end
end

app/helpers/nodes_helper.rb
module NodesHelper
end

app/views/nodes/_form.html.erb
<%= form_for(@node) do |f| %>
  <% if @node.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@node.errors.count, "error") %> prohibited this node from being saved:</h2>

      <ul>
      <% @node.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tree_id %><br>
    <%= f.text_field :tree_id %>
  </div>
  <div class="field">
    <%= f.label :variable %><br>
    <%= f.text_field :variable %>
  </div>
  <div class="field">
    <%= f.label :condition %><br>
    <%= f.text_field :condition %>
  </div>
  <div class="field">
    <%= f.label :result %><br>
    <%= f.text_field :result %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.number_field :level %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nodes/cenario_resultado.html.erb
<p id="notice"><%= notice %></p>
<div class="col-sm-12">
  <h1>Escolha o tipo de busca</h1>
  <div class="container-fluid">
    <ul class="nav nav-tabs">
      <li><a href="/cenario/<%= @id %>">Busca por atributos</a></li>
      <li class="active"><a href="#">Busca por produtividade</a></li>
    </ul>

    <div class="row">
      <div id="results" class="col-sm-6">
        <table>
          <thead>
            <tr>
              <th>Produtividade</th>
            </tr>
          </thead>

          <tbody>
            <% @results.each do |result| %>
            <tr>
              <td ><a class="resultado" id="<%= result %>" href=""><%= result %></a></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div id="paths" class="col-sm-6">
        <section class="acordeon-result">

          <div class="ac">

            <input class="ac-input" id="ac-0" name="ac-0" type="checkbox" checked="checked" />
            <label class="ac-label" for="ac-0">Resultados</label>

          </div><!--/ac-->

        </section>
      </div>
      <div>
        <input type="text" placeholder="Titulo do Cenario" id="title_scenario">
        <button type="button" id="salvar" data-id="" class="btn btn-success">Salvar</button>
      </div>
    </div>
  </div>
</div>

app/views/nodes/edit.html.erb
<h1>Editing Node</h1>

<%= render 'form' %>

<%= link_to 'Show', @node %> |
<%= link_to 'Back', nodes_path %>

app/views/nodes/index.html.erb
<p id="notice"><%= notice %></p>
<div class="col-sm-12">
  <h1>Escolha o tipo de busca</h1>
  <div class="container-fluid">
    <ul class="nav nav-tabs">
      <li class="active"><a href="#">Busca por atributos</a></li>
      <li><a href="/cenario_resultado/<%= @id %>">Busca por produtividade</a></li>
    </ul>

    <div class="row">
      <div class="col-sm-8">
        <div class="row mg-t-20">
          <div class="col-sm-4">
            <strong>Variáveis</strong>
          </div>
          <div class="col-sm-8">
            <strong>Condições</strong>
          </div>
        </div>

        <div class="row mg-t-10">
          <div class="col-sm-12">
            <% @nodes.each do |key,value| %>
              <div class="row mg-b-15">
                <div class="col-sm-4">
                  <%= key.to_s.humanize %>
                </div>
                <div class="col-sm-8">
                  <select name="<%=key%>" id="<%=key%>" class="node-value-selector form-control">
                    <option value="" class="node-value-selector form-control">selecione uma opcao</option>
                    <% value.each do |node|%>
                      <option value="<%=node.name%>" data-result="<%=node.result%>" data-tree="<%=@id%>" class="node-value-selector form-control" ><%=node.name%></option>
                    <% end %>
                    </option>
                  </select>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-sm-4">
        <h2>Produtividade:</h2>
          <div id="final_result">

          </div>
        <div class="col-sm-12">
          <h2>Escolhas:</h2>
          <div>
            <ul id="escolhas">

            </ul>
          </div>
        </div>
      </div>

    </div>

  </div>
</div>

app/views/nodes/new.html.erb
<h1>New Node</h1>

<%= render 'form' %>

<%= link_to 'Back', nodes_path %>

app/views/nodes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Tree:</strong>
  <%= @node.tree %>
</p>

<p>
  <strong>Variable:</strong>
  <%= @node.variable %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @node.condition %>
</p>

<p>
  <strong>Result:</strong>
  <%= @node.result %>
</p>

<p>
  <strong>Level:</strong>
  <%= @node.level %>
</p>

<%= link_to 'Edit', edit_node_path(@node) %> |
<%= link_to 'Back', nodes_path %>