config/routes.rb
Rails.application.routes.draw do

  root 'trees#index'

  resources :scenarios
  devise_for :users

  scope '/admin' do
    resources :users
  end

  resources :trees
  get '/cenario/:tree_id', to: 'nodes#cenario'
  post '/conditions_sub_trees', to: 'nodes#conditions_sub_trees'
  get '/cenario_resultado/:tree_id', to: 'nodes#cenario_resultado'
  post '/path_for_result', to: 'nodes#path_for_result'

end

app/views/layouts/_messages.html.erb
<div class="col-sm-12">

<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "danger" : "success" %>" role="alert">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand mb-0" href="#">SECC</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->

    <% if !current_user.nil? %>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav-item"><%= link_to 'Minhas Árvores', trees_path %></li>
        <li class="nav-item"><%= link_to 'Meus Cenários', scenarios_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ações <span class="caret"></span></a>
          <ul class="dropdown-menu">
          <%if current_user.is_admin? %>
            <li><a href="<%=users_path%>">Gerenciar usuários</a></li>
          <%end%>
            <li><a href="<%=edit_user_path(current_user)%>">Editar dados Cadastrados</a></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Sair", destroy_user_session_path, method: :delete %>﻿</li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
    <%end%>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Myapp" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>